CONFIG_FILE: str = "config.json"
DOCKER_NAMESPACE: str = "pdfix"
DOCKER_REPOSITORY: str = "generate-alternate-text-blip-large"
DOCKER_IMAGE: str = f"{DOCKER_NAMESPACE}/{DOCKER_REPOSITORY}"
IMAGE_FILE_EXT_REGEX: str = r"\.(jpg|jpeg|png|bmp)$"
SUPPORTED_IMAGE_EXT: str = ".jpg .jpeg .png .bmp"
